// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpxgepvodrhbmskunhph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpweGdlcHZvZHJoYm1za3VuaHBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDM5NjksImV4cCI6MjA2MjAxOTk2OX0.eYIKphOu5MHOss6AjVTo3oY7mbyiZ1PSE0e1tjBjtC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);